### ISSUE TITLE
RPM app likely useless after new website update

### ISSUE THREAD

**Issue by a-catgirl-dev** [Gameplex-Software/RPM-Android-App#1]
Open rpm on your phone. it always gives you pricing

next time how about we load panel.gameplexsoftware.com instead of .com/rpm (rpm leads to pricing)

FIX:
undo rpm leading to pricing OR
update the app to load panel.gameplexsoftware.com

**Comment by tristanpoland** [comment]
Should be fixed with a backend server reconfiguration, if it is, please mark as closed.
